In [18]:
import pandas as pd
from ml.data import process_data
from ml.model import compute_model_metrics, inference
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer, OneHotEncoder, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
import os

In [57]:
# Add code to load in the data, model and encoder
df = pd.read_csv("data/raw/census.csv")
df.columns = df.columns.str.strip()
df = df.drop_duplicates()
model = pd.read_pickle(r"model.pkl")
encoder = pd.read_pickle(r"encoder.pkl") 
# lb = pd.read_pickle(r"lb.pkl")

In [47]:
def train_model(X_train, y_train):
    """
    Trains a machine learning model and returns it.
    Inputs
    ------
    X_train : np.array
        Training data.
    y_train : np.array
        Labels.
    Returns
    -------
    model
        Trained machine learning model.
    """
    model = RandomForestClassifier(min_samples_split=20, max_features='sqrt')
    # model = RandomForestClassifier()
    model.fit(X_train,y_train)
    return model

In [58]:
train_set, test_set = train_test_split(df, test_size=0.20, random_state=42, stratify=df.salary)


cat_features = [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country",
]

In [ ]:
# X_train, y_train, encoder, lb = process_data(
# train_set, categorical_features=cat_features, label="salary", training=True
#     )
# # Train and save a model.
# model = train_model(X_train, y_train)

In [59]:
test_set.head()

,age,workclass,fnlgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
20334,27,Private,178709,Masters,14,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
23878,51,Local-gov,387250,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,50,United-States,>50K
19996,34,Private,202498,12th,8,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Dominican-Republic,<=50K
21440,31,Private,133861,Assoc-acdm,12,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,40,United-States,<=50K
10000,34,Private,120461,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,50,United-States,<=50K

In [60]:
lb = LabelEncoder() 
test_set['salary'] = lb.fit_transform(test_set['salary'])

In [61]:
test_set.head()

,age,workclass,fnlgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
20334,27,Private,178709,Masters,14,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,0
23878,51,Local-gov,387250,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,50,United-States,1
19996,34,Private,202498,12th,8,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Dominican-Republic,0
21440,31,Private,133861,Assoc-acdm,12,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,40,United-States,0
10000,34,Private,120461,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,50,United-States,0

In [62]:
len(test_set)

6508

In [63]:
print(test_set.salary.unique())

[0 1]

In [64]:
# y =X_test.iloc[:,-1:]
# lb = LabelEncoder() 
# y = lb.fit_transform(np.ravel(y))

In [65]:
# _ , test_set = train_test_split(df, test_size=0.20, random_state=42, stratify=df.salary)
# lb = LabelEncoder() 
#             y = lb.fit_transform(np.ravel(y))


X_test, y_test, _, _ = process_data(
                test_set,
                cat_features,
                label= None, encoder=encoder, lb=lb, training=False)
y_preds=inference(model, X_test)
y =X_test.iloc[:,-1:]
# lb = LabelEncoder() 
# y = lb.fit_transform(np.ravel(y))
prc, rcl, fb = compute_model_metrics(y, y_preds)

print(pcr, rcl, fb)

ValueError: X has 109 features, but RandomForestClassifier is expecting 108 features as input.